### PR TITLE
Primitive killaura

### LINKED ISSUE #31: killaura example?
For mob farms will be great to have simplest hostile mobs killaura example for easy deploy

### PR DESCRIPTION
**Pull request by maxsupermanhd**
Improved usage messages. Added simplest killaura I could make, looks like working fine.

Improvements that can be made:
- Send animation when attacking (looks unnatural but works)
- Rotate bot head towards block he is facing (works without it but obviously strange looking)
- Check for entity type and name (not possible right now without modifying EntityManager as I see)

Fixes #31

### CODE REVIEW

**Comment by adepierre** [comment]
Thanks for the PR!

Could you please elaborate on the chat parsing modification? You seem to search for an extra array in the json, and return an error if not present. But according to the [wiki](https://wiki.vg/Chat#Standard_chat_message), no extra is required to get an actual message. So I'm curious about this modification. Is this specific to a modded version of the game?

**Comment by maxsupermanhd** [comment]
Yes, most servers (all of them except vanilla) pass "text" field as empty. Actual java client uses only extra to render messages.

**Comment by adepierre** [comment]
Well the point of Botcraft is to handle vannila servers, not modded ones so I can't merge a PR that basically just breaks everything because modded servers don't follow vanilla :/

**Comment by maxsupermanhd** [comment]
Well, I completely disagree with this - "extra" field contains literally same message but with formatting applied to it (color and effects) and it is supported and used in vanilla server as well. Vanilla client read "extra" and we should read it too.

**Comment by maxsupermanhd** [comment]
Actually after deeper inspection it appears that *some* servers combine both, my bad then, I should concatenate main part of the message and only then append extra to it. I will push a fix soon.

**Comment by maxsupermanhd** [comment]
Also having "110% vanilla" approach does not mean ignoring half of the protocol as "extra" ignored here :confused:

**Comment by maxsupermanhd** [comment]
Actually I just now realized that this is not issue of chat command example but `Chat::ParseChat` just parsing chat wrong, will move whole thing...

**Comment by adepierre** [comment]
I totally agree with you that supporting only vanilla and ignoring unused parts of the protocol is **not** the approach to follow. However, breaking compatibility with vanilla to support modded servers is also a no go.

You are right about the ``ParseChat`` function, that's where this stuff should go. I wrote that a long time ago now, and indeed it lacks the support for all the chat abilities, because I didn't think that having colors or formatting was important. But indeed, extra texts are a good add here.

**Comment by maxsupermanhd** [comment]
All this chat hell smells like it should go to different pull request tbh, `Chat::ParseChat` is parsing "text" field only when it is present on "translation" within "with" object, that's the reason it is straight not working on other servers that rely on client displaying object properly. I will remove all chat modifications from here and make it in different pull request...

**Comment by maxsupermanhd** [comment]
Requesting a review

**Comment by adepierre** [comment]
I've reviewed your code, I think you've got an extra ``continue;`` that you could remove and you're missing a mutex lock when you're looping through your entities to ensure the vector is not changed while you're iterating it, but beside that it should be ok.

However, I'm a bit reluctant to merge it into master at the moment. Don't get me wrong, I'm thankful for the PR and glad it works for you, but there are two main reasons for that:

1. I'm currently refactoring the AI system so ``InterfaceClient`` is in the process to be entirely changed. Si I'd rather integrate the modifications once it's done rather than doing it twice.
2. I don't think that this example should be used. It certainly works, but it also attacks every single entity on the given block. Which means that the server receives an attack packet for each mob, minecart, item and even XP orb every ``delay``. This can potentially be pretty bad, and that's why I wanted to have a proper entity system before implementing something like that. But there are a **lot** of different entities in this game, each of them having their own properties, so it's quite hard to find a nice and clean way to implement it.

**Comment by maxsupermanhd** [comment]
Oh, my bad, this extra continue was supposed to be a `break`, also I don't see a need for a mutex in this situation, even if they move while I am looping through them it is how it supposed to work, if it moves - it moves.
For now as I understood, entity manager does not have any info about type of entity - if I can get this info then applying filters will be essential part of killaura.

**Comment by adepierre** [comment]
You need the mutex in case the vector of entities is modified during your loop (like if an entity is removed for example).

Yes that's what I said, there is no proper support for entities in botcraft, so that's why I'm not sure this is a good example to add.

**Comment by adepierre** [comment]
Example 5 does that now.

**Pull request closed without merging**
