### PR TITLE
I fixed the chat command client which was not working

### PR DESCRIPTION
**Pull request by Darker**
There was unfinished code in chat client, I finished the code to split the message in sub strings. The current message parser was also not working. My fix does not completely cover everything that can appear in the JSON, but at least now `message.GetText()` does not return empty string.

### CODE REVIEW

**Comment by Darker** [comment]
Oh, and I also added editorconfig. VS and other editors respect it over their internal settings - in my project in C++ I usually use just 2 spaces, this will help me and other contributors respect the project code style.

**Comment by adepierre** [comment]
Hi!

You're not the first one trying to "fix" that. I assume you tested it on a non-vanilla server (my best guess is Paper), saw it didn't work and worked from here to make it work.

The idea is good, because indeed, botcraft doesn't support all the chat cases described on the wiki at the moment. Unfortunately, by doing so, you also broke a working example. With your PR, ChatCommand example doesn't work anymore on a vanilla server. So you just dropped support of vanilla servers to add support for _some_ non-vanilla ones.

I'm trying to get botcraft to work first on vanilla servers, and then, if possible, to custom servers and modded ones. But vanilla comes first.

One day I'll try to add full support for all chat features and it should allow it to work on both vanilla and paper. But right now, only vanilla is supported _for the chat messages_.

**Comment by Darker** [comment]
I get it. I will check what the vanilla server does and make sure it works in both cases. I also see I misunderstood the code in the demo and assumed it does not work, so I will restore that.

**Comment by adepierre** [comment]
Any news about that or should I close the PR ?

**Comment by Darker** [comment]
Hi, close it for now probably. I made a bunch of mistakes regarding how I cloned this repo and started editing it and also pushed bunch of bad code into it. I'll take look at this but first I need to clean up the mess and probably fork again clean.

**Pull request closed without merging**
